### ISSUE TITLE
What is the status of this app? 

### ISSUE THREAD

**Issue by flothesof** [aplouis/PhotoApplication#1]
Hi there,
I've noticed a lack of open-source Android collage apps (for instance looking in the F Droid store). 
What is the current status of your project? 
Has it reached a stage where it is usable by others? It would be great if your work could fill that gap. 
Best regards 
Florian

**Comment by aplouis** [comment]
> Hi there,
> I've noticed a lack of open-source Android collage apps (for instance looking in the F Droid store).
> What is the current status of your project?
> Has it reached a stage where it is usable by others? It would be great if your work could fill that gap.
> Best regards
> Florian

Florian, thanks for your question.  I have not updated the project in a couple of years and it isn't actively being worked on.  I believe it is using an older camera api but the logic is still in production as a module in a larger application.
Alex

**Comment by flothesof** [comment]
Thank you for your answer!
